version: '3.7'

services:
  spring-demo-authsrv:
    image: eclipse-temurin:18
    ports:
      - "9000:9000"
    volumes:
      - $PWD/mp_authsrv_gradlecache:/root/.gradle
      - $PWD/mp_authsrv_app:/root/app
    stdin_open: false
    tty: false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /root/app
    command: ./gradlew :mod_auth_server:run

  spring-demo-rscsrv:
    image: eclipse-temurin:18
    ports:
      - "8090:8090"
    volumes:
      - $PWD/mp_rscsrv_gradlecache:/root/.gradle
      - $PWD/mp_rscsrv_app:/root/app
    stdin_open: false
    tty: false
    depends_on:
      - spring-demo-authsrv
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /root/app
    command: ./gradlew :mod_resource_server:run

  spring-demo-webclient:
    image: eclipse-temurin:18
    ports:
      - "8080:8080"
    volumes:
      - $PWD/mp_webclient_gradlecache:/root/.gradle
      - $PWD/mp_webclient_app:/root/app
    stdin_open: false
    tty: false
    depends_on:
      - spring-demo-authsrv
      - spring-demo-rscsrv
    working_dir: /root/app
    command: ./gradlew :mod_webclient:run
