version: '3.7'

services:
  spring-demo-mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      #- $PWD/mp_mongodb_data:/data/db
      - $PWD/mp_mongodb_user_setup/create_user-authsrv.js:/docker-entrypoint-initdb.d/create_user-authsrv.js:ro
      - $PWD/mp_mongodb_user_setup/create_user-rscsrv.js:/docker-entrypoint-initdb.d/create_user-rscsrv.js:ro
    restart: always
    stdin_open: false
    tty: false
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: abcd
      MONGO_INITDB_DATABASE: admin

  spring-demo-mongo-express:
    image: mongo-express
    ports:
      - "8070:8081"
    restart: always
    stdin_open: false
    tty: false
    depends_on:
      - spring-demo-mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: abcd
      ME_CONFIG_MONGODB_URL: mongodb://root:abcd@spring-demo-mongo:27017/admin
